# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: oxmel.sh
email: your-email@example.com
tagline:
description: >- # this means to ignore newlines until "baseurl:"
  Journal de bord d'un développeur amateur en quête d'une élévation de privilèges.
  Peut contenir des traces de Python, Bash et Linux.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oxmel.sh" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 0xm3l
github_username:  Oxmel
rss: RSS

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Metadata (handled by the plugin 'seo-tag')
author:
  name: Oxmel
  twitter: 0xm3l
twitter:
  username: 0xm3l
  card: summary
social:
  name: Oxmel
  links:
    - https://twitter.com/0xm3l
    - https://github.com/Oxmel

# Navigation menu
header_pages:
  - home.md
  - tags.html
  - archives.html
  - about.md
  - contact.md

# Set a default layout for every posts so we don't have to manually declare it
# each time. We also add a default tag but if one or more tags are declared in
# the post header they'll override it.
#
# Note : With categories the default value is added to the list instead of
# being overriden. But a workaround consists of using the variable 'category'
# instead of 'categories' both in the config file and in the post header.
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      tags: "untagged"
      image: /assets/images/default-card.jpg

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Display the post url under the form '/category/slug', or simply '/slug'
# if no category has been specified. That way we can have a more fine grained
# and adaptable title management. If no slug is specified in the post header,
# the post title will be used instead.
#permalink: /:categories/:slug
permalink: /:slug

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
